services:
  mysql:
    image: mysql:8.0
    container_name: weather-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weather-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: Asia/Jakarta
    ports:
      - "3306:3306"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: weather-redis
    ports:
      - "6379:6379"
