version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: weather-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weather-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: weather-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: weather-server
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      MYSQL_DSN: "admin:admin@tcp(mysql:3306)/weather-db"
      REDIS_ADDR: "redis:6379"
      PORT: "8080"
    ports:
      - "8080:8080"
