// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	weather "tyarus/weather-app/pkg/weather"

	mock "github.com/stretchr/testify/mock"
)

// WeatherAPIClientInterface is an autogenerated mock type for the WeatherAPIClientInterface type
type WeatherAPIClientInterface struct {
	mock.Mock
}

// GetForecast provides a mock function with given fields: location, day
func (_m *WeatherAPIClientInterface) GetForecast(location string, day int) (*weather.ForecastResponse, error) {
	ret := _m.Called(location, day)

	if len(ret) == 0 {
		panic("no return value specified for GetForecast")
	}

	var r0 *weather.ForecastResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (*weather.ForecastResponse, error)); ok {
		return rf(location, day)
	}
	if rf, ok := ret.Get(0).(func(string, int) *weather.ForecastResponse); ok {
		r0 = rf(location, day)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*weather.ForecastResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(location, day)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWeatherAPIClientInterface creates a new instance of WeatherAPIClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWeatherAPIClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *WeatherAPIClientInterface {
	mock := &WeatherAPIClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
